### PR TITLE
Devel pc

### PR DESCRIPTION
**Pull request by phoebsc**
Fixed bugs:
1. OSC values are all ones. -- changed OSC initialization in correlation_perfreq.py
2. only loading one datastream from SMARTING EEG system. -- changed stream ID to be 'source_id'+'uid'
3. rvalues are all ones for EMOTIV EEG system. -- zscore every analysis window
4. threads don't exit properly -- added thread handling upon exit

New features:
1. Drop down menu for changing window size

### CODE REVIEW

**Comment by dmedine** [comment]
I am afraid that the problem of the application not exiting problem still exists. Is it possible that these changes weren't committed? I don't see any commit message related to this bugfix in the commit history.

I noticed one other issue. When sending random values the output of the analysis appeared to be numbers in the vicinity of .4, but when I run the analysis on random sample generator from the devel-PC branch, I get values closer to .2. It seems like the output should be very nearly the same in either case.

Screenshot of master branch in action:
master

Screenshot of devel-PC branch in action:
devel-PC

**Comment by phoebsc** [comment]
Hi,

Yes it's not yet committed. I created the request but still need to resolve conflicts... 

For the rvalues: when debugging EMOTIV I found the data array wasn't reshaped properly, so actually the values have been wrong... I've now fixed this here https://github.com/RhythmsOfRelating/HybridHarmony/blob/0e56d5f2b6052b663a1e7fa40f2c6989992fc48a/src/analysis/correlation_perFreq.py#L196

-- which indeed calls for tests!

**Comment by phoebsc** [comment]
Besides, I also added zscoring to the analysis window (see above), which can shift the values. However, the change you saw I believe is because of the reshaping issue, since random values are relatively stable.

**Comment by dmedine** [comment]
> Yes it's not yet committed. I created the request but still need to resolve conflicts...

Ok. We can also do it like this:

1. Merge this pull request
2. rebase devel branch onto master
3. commit thread exit fix
4. submit new PR

I believe that should stop any conflicts.

Or did you mean the conflicts in analysis.py and correlation_perFreq.py that exist in this merge? I can resolve those and push to master if you are happy with this merge (see comments about testing below).

**Comment by dmedine** [comment]
> Besides, I also added zscoring to the analysis window (see above), which can shift the values. However, the change you saw I believe is because of the reshaping issue, since random values are relatively stable.

Ok. This is good. I admit that I have kind of lost track of what is actually happening here. The code is quite terse (which is good from a programming point of view, but bad from a 'what the heck is happening here?' point of view). 

Can you explain the tests you are running? I have been thinking about a way to generate a  pair of 'ground truth' signals that always generate an expected output if the analysis procedure is indeed correct. Maybe one signal is a steady pulse and the other is a modulated pulse that coincides with the steady pulse in a regular way (if that makes sense). The output would then vary between rvalues of 0 and 1 as the pulses become more and less similar. 

In any case, I feel nervous about how 'correct' we are being. I would like to have a ground truth to test on---but maybe you have already established this. It seems to me that each frequency band of a random signal should have pretty similar correlation values, but the beta band seems to be consistently lower than alpha and theta.

**Pull request merged**
